-- Conditions, so that a turn past the easy rounds asks for more than one thing.
--
-- The whole object catalogue was one target at a time, which stopped being a
-- hunt once a player knew their own room. From here:
--
--   easy    one thing, exactly as before
--   medium  two things held in the same frame
--   hard    a rarer pair, three things, or three of the same
--
-- Nothing is retired: every quest that used to be medium or hard is still drawn,
-- it is just an easy round now, which also makes rounds 1-2 far less repetitive.
--
-- The requirement rides in `validator_config` rather than a new column, because
-- that column already reaches both the vision service and the browser untouched
-- by the RPC and the PostgREST select in between. `targetClasses` is the list
-- that must be in shot at once - a class repeated in it is how "two of these"
-- is written - and `targetLabels` names each one for the screen. `target_class`
-- stays set to the first of them, which is what the table check and the
-- background-avoidance ordering in prepare_turn read.

update public.quests
set difficulty = 'easy'
where kind in ('object', 'color') and difficulty <> 'easy';

-- Holding two things in one frame is the difficulty. Asking for the same 0.55
-- per-object confidence on top of that would lose fair attempts to one weak
-- reading, so each object is judged a little more leniently than a solo one.
insert into public.quests
  (id, key, label, prompt, kind, difficulty, target_class, environments, portable, validator_config)
values
  ('30000000-0000-4000-8000-000000000001', 'combo-phone-bottle', 'Утас + Лонх', 'УТАС БА ЛОНХ ЗЭРЭГ', 'object', 'medium', 'cell phone', array['school', 'home', 'outdoor']::public.game_environment[], true, '{"targetClasses": ["cell phone", "bottle"], "targetLabels": ["Утас", "Лонх"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000002', 'combo-person-bottle', 'Хүн + Лонх', 'ХҮН БА ЛОНХ ЗЭРЭГ', 'object', 'medium', 'person', array['school', 'home', 'outdoor']::public.game_environment[], true, '{"targetClasses": ["person", "bottle"], "targetLabels": ["Хүн", "Лонх"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000003', 'combo-two-bottles', 'Хоёр лонх', 'ХОЁР ЛОНХ ЗЭРЭГ', 'object', 'medium', 'bottle', array['school', 'home', 'outdoor']::public.game_environment[], true, '{"targetClasses": ["bottle", "bottle"], "targetLabels": ["Лонх", "Лонх"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000004', 'combo-backpack-phone', 'Үүргэвч + Утас', 'ҮҮРГЭВЧ БА УТАС ЗЭРЭГ', 'object', 'medium', 'backpack', array['school', 'home', 'outdoor']::public.game_environment[], true, '{"targetClasses": ["backpack", "cell phone"], "targetLabels": ["Үүргэвч", "Утас"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000005', 'combo-book-cup', 'Ном + Аяга', 'НОМ БА АЯГА ЗЭРЭГ', 'object', 'medium', 'book', array['school', 'home']::public.game_environment[], true, '{"targetClasses": ["book", "cup"], "targetLabels": ["Ном", "Аяга"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000006', 'combo-chair-book', 'Сандал + Ном', 'САНДАЛ БА НОМ ЗЭРЭГ', 'object', 'medium', 'chair', array['school', 'home']::public.game_environment[], false, '{"targetClasses": ["chair", "book"], "targetLabels": ["Сандал", "Ном"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000007', 'combo-laptop-phone', 'Компьютер + Утас', 'КОМПЬЮТЕР БА УТАС ЗЭРЭГ', 'object', 'medium', 'laptop', array['school', 'home']::public.game_environment[], true, '{"targetClasses": ["laptop", "cell phone"], "targetLabels": ["Компьютер", "Утас"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000008', 'combo-table-cup', 'Ширээ + Аяга', 'ШИРЭЭ БА АЯГА ЗЭРЭГ', 'object', 'medium', 'dining table', array['school', 'home']::public.game_environment[], false, '{"targetClasses": ["dining table", "cup"], "targetLabels": ["Ширээ", "Аяга"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000009', 'combo-two-chairs', 'Хоёр сандал', 'ХОЁР САНДАЛ ЗЭРЭГ', 'object', 'medium', 'chair', array['school', 'home']::public.game_environment[], false, '{"targetClasses": ["chair", "chair"], "targetLabels": ["Сандал", "Сандал"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000010', 'combo-backpack-book', 'Үүргэвч + Ном', 'ҮҮРГЭВЧ БА НОМ ЗЭРЭГ', 'object', 'medium', 'backpack', array['school', 'home']::public.game_environment[], true, '{"targetClasses": ["backpack", "book"], "targetLabels": ["Үүргэвч", "Ном"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000011', 'combo-couch-tv', 'Буйдан + Телевиз', 'БУЙДАН БА ТЕЛЕВИЗ ЗЭРЭГ', 'object', 'medium', 'couch', array['home']::public.game_environment[], false, '{"targetClasses": ["couch", "tv"], "targetLabels": ["Буйдан", "Телевиз"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000012', 'combo-bowl-spoon', 'Таваг + Халбага', 'ТАВАГ БА ХАЛБАГА ЗЭРЭГ', 'object', 'medium', 'bowl', array['home']::public.game_environment[], true, '{"targetClasses": ["bowl", "spoon"], "targetLabels": ["Таваг", "Халбага"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000013', 'combo-cup-spoon', 'Аяга + Халбага', 'АЯГА БА ХАЛБАГА ЗЭРЭГ', 'object', 'medium', 'cup', array['home']::public.game_environment[], true, '{"targetClasses": ["cup", "spoon"], "targetLabels": ["Аяга", "Халбага"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000014', 'combo-fridge-bottle', 'Хөргөгч + Лонх', 'ХӨРГӨГЧ БА ЛОНХ ЗЭРЭГ', 'object', 'medium', 'refrigerator', array['home']::public.game_environment[], false, '{"targetClasses": ["refrigerator", "bottle"], "targetLabels": ["Хөргөгч", "Лонх"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000015', 'combo-car-person', 'Машин + Хүн', 'МАШИН БА ХҮН ЗЭРЭГ', 'object', 'medium', 'car', array['outdoor']::public.game_environment[], false, '{"targetClasses": ["car", "person"], "targetLabels": ["Машин", "Хүн"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000016', 'combo-bicycle-person', 'Дугуй + Хүн', 'ДУГУЙ БА ХҮН ЗЭРЭГ', 'object', 'medium', 'bicycle', array['outdoor']::public.game_environment[], false, '{"targetClasses": ["bicycle", "person"], "targetLabels": ["Дугуй", "Хүн"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000017', 'combo-two-cars', 'Хоёр машин', 'ХОЁР МАШИН ЗЭРЭГ', 'object', 'medium', 'car', array['outdoor']::public.game_environment[], false, '{"targetClasses": ["car", "car"], "targetLabels": ["Машин", "Машин"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000018', 'combo-bench-person', 'Сандал + Хүн', 'ГУДАМЖНЫ САНДАЛ БА ХҮН ЗЭРЭГ', 'object', 'medium', 'bench', array['outdoor']::public.game_environment[], false, '{"targetClasses": ["bench", "person"], "targetLabels": ["Сандал", "Хүн"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000019', 'combo-car-traffic-light', 'Машин + Гэрлэн дохио', 'МАШИН БА ГЭРЛЭН ДОХИО ЗЭРЭГ', 'object', 'medium', 'car', array['outdoor']::public.game_environment[], false, '{"targetClasses": ["car", "traffic light"], "targetLabels": ["Машин", "Гэрлэн дохио"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000020', 'combo-three-bottles', 'Гурван лонх', 'ГУРВАН ЛОНХ ЗЭРЭГ', 'object', 'hard', 'bottle', array['school', 'home', 'outdoor']::public.game_environment[], true, '{"targetClasses": ["bottle", "bottle", "bottle"], "targetLabels": ["Лонх", "Лонх", "Лонх"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000021', 'combo-phone-book-bottle', 'Утас + Ном + Лонх', 'УТАС, НОМ, ЛОНХ ЗЭРЭГ', 'object', 'hard', 'cell phone', array['school', 'home']::public.game_environment[], true, '{"targetClasses": ["cell phone", "book", "bottle"], "targetLabels": ["Утас", "Ном", "Лонх"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000022', 'combo-keyboard-mouse', 'Keyboard + Mouse', 'KEYBOARD БА MOUSE ЗЭРЭГ', 'object', 'hard', 'keyboard', array['school', 'home']::public.game_environment[], true, '{"targetClasses": ["keyboard", "mouse"], "targetLabels": ["Keyboard", "Mouse"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000023', 'combo-laptop-mouse-cup', 'Компьютер + Mouse + Аяга', 'КОМПЬЮТЕР, MOUSE, АЯГА ЗЭРЭГ', 'object', 'hard', 'laptop', array['school', 'home']::public.game_environment[], true, '{"targetClasses": ["laptop", "mouse", "cup"], "targetLabels": ["Компьютер", "Mouse", "Аяга"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000024', 'combo-scissors-book', 'Хайч + Ном', 'ХАЙЧ БА НОМ ЗЭРЭГ', 'object', 'hard', 'scissors', array['school', 'home']::public.game_environment[], true, '{"targetClasses": ["scissors", "book"], "targetLabels": ["Хайч", "Ном"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000025', 'combo-keyboard-phone', 'Keyboard + Утас', 'KEYBOARD БА УТАС ЗЭРЭГ', 'object', 'hard', 'keyboard', array['school', 'home']::public.game_environment[], true, '{"targetClasses": ["keyboard", "cell phone"], "targetLabels": ["Keyboard", "Утас"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000026', 'combo-tie-person', 'Зангиа + Хүн', 'ЗАНГИА БА ХҮН ЗЭРЭГ', 'object', 'hard', 'tie', array['school']::public.game_environment[], false, '{"targetClasses": ["tie", "person"], "targetLabels": ["Зангиа", "Хүн"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000027', 'combo-vase-plant', 'Ваар + Цэцэг', 'ВААР БА ЦЭЦЭГ ЗЭРЭГ', 'object', 'hard', 'vase', array['home']::public.game_environment[], true, '{"targetClasses": ["vase", "potted plant"], "targetLabels": ["Ваар", "Цэцэг"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000028', 'combo-wine-glass-bottle', 'Хундага + Лонх', 'ХУНДАГА БА ЛОНХ ЗЭРЭГ', 'object', 'hard', 'wine glass', array['home']::public.game_environment[], true, '{"targetClasses": ["wine glass", "bottle"], "targetLabels": ["Хундага", "Лонх"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000029', 'combo-teddy-bed', 'Баавгай + Ор', 'БААВГАЙ БА ОР ЗЭРЭГ', 'object', 'hard', 'teddy bear', array['home']::public.game_environment[], false, '{"targetClasses": ["teddy bear", "bed"], "targetLabels": ["Баавгай", "Ор"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000030', 'combo-fork-knife-spoon', 'Сэрээ + Хутга + Халбага', 'СЭРЭЭ, ХУТГА, ХАЛБАГА ЗЭРЭГ', 'object', 'hard', 'fork', array['home']::public.game_environment[], true, '{"targetClasses": ["fork", "knife", "spoon"], "targetLabels": ["Сэрээ", "Хутга", "Халбага"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000031', 'combo-toothbrush-cup', 'Сойз + Аяга', 'СОЙЗ БА АЯГА ЗЭРЭГ', 'object', 'hard', 'toothbrush', array['home']::public.game_environment[], true, '{"targetClasses": ["toothbrush", "cup"], "targetLabels": ["Сойз", "Аяга"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000032', 'combo-motorcycle-person', 'Мотоцикль + Хүн', 'МОТОЦИКЛЬ БА ХҮН ЗЭРЭГ', 'object', 'hard', 'motorcycle', array['outdoor']::public.game_environment[], false, '{"targetClasses": ["motorcycle", "person"], "targetLabels": ["Мотоцикль", "Хүн"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000033', 'combo-stop-sign-car', 'Зогсох тэмдэг + Машин', 'ЗОГСОХ ТЭМДЭГ БА МАШИН ЗЭРЭГ', 'object', 'hard', 'stop sign', array['outdoor']::public.game_environment[], false, '{"targetClasses": ["stop sign", "car"], "targetLabels": ["Зогсох тэмдэг", "Машин"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000034', 'combo-three-cars', 'Гурван машин', 'ГУРВАН МАШИН ЗЭРЭГ', 'object', 'hard', 'car', array['outdoor']::public.game_environment[], false, '{"targetClasses": ["car", "car", "car"], "targetLabels": ["Машин", "Машин", "Машин"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000035', 'combo-dog-person', 'Нохой + Хүн', 'НОХОЙ БА ХҮН ЗЭРЭГ', 'object', 'hard', 'dog', array['outdoor']::public.game_environment[], false, '{"targetClasses": ["dog", "person"], "targetLabels": ["Нохой", "Хүн"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb),
  ('30000000-0000-4000-8000-000000000036', 'combo-bicycle-car', 'Дугуй + Машин', 'ДУГУЙ БА МАШИН ЗЭРЭГ', 'object', 'hard', 'bicycle', array['outdoor']::public.game_environment[], false, '{"targetClasses": ["bicycle", "car"], "targetLabels": ["Дугуй", "Машин"], "confidence": 0.5, "borderlineMin": 0.45, "consensus": 2}'::jsonb);
